{
  "hash": "a99a7cd5d3517966f5b52a4aa50b4bf2",
  "result": {
    "engine": "knitr",
    "markdown": "\n# Packages and Datasets\n***\n\nThe book works from a small number of datasets on purpose.\nReusing `USArrests` across twenty chapters means that by the time you reach multiple regression you already know what the variables are, so the new material is the only new thing on the page.\nThis appendix lists each dataset, its variables, where it comes from, and which chapters use it.\nUse it when a chapter refers to a variable you have forgotten, or when you want a dataset you already understand for an exercise.\nThe last section lists every package the book uses, so you can install them all before you start.\n\n## Summary\n\n| Dataset | Source | Rows | Variables | Chapters |\n|---|---|---:|---|---|\n| `USArrests` | `datasets` (built in) | 50 | `Murder`, `Assault`, `UrbanPop`, `Rape` | 2--3, 5--8, 10--11, 13--18, 20--25, 30 |\n| `state.region` | `datasets` (built in) | 50 | a 4-level factor | 3, 13, 22, 24, 30 |\n| `anscombe` | `datasets` (built in) | 11 | `x1`--`x4`, `y1`--`y4` | 15 |\n| `UCBAdmissions` | `datasets` (built in) | 24 cells | `Admit`, `Gender`, `Dept` | 18, 22 |\n| `LifeCycleSavings` | `datasets` (built in) | 50 | `sr`, `pop15`, `pop75`, `dpi`, `ddpi` | 22 |\n| `Wages1` | `Ecdat` | 3294 | `exper`, `sex`, `school`, `wage` | 2, 5--8, 11--18, 20, 22, 26 |\n| `finance-charts-apple.csv` | web, via `read.csv` | 506 | `Date`, `AAPL.Open`, `AAPL.High`, `AAPL.Low`, `AAPL.Close`, `AAPL.Volume`, `AAPL.Adjusted`, and four derived columns | 27 |\n| `tylervigen.csv` | web, via `read.csv` | varies | many unrelated time series | 29 |\n\n## Built-in Datasets\n\nThese come with R, so they need no package and no download.\nType the name to see the data, and `?USArrests` for the help page.\n\n#### **USArrests** {-}\n\nViolent crime rates by US state in 1973, and the book's main working dataset.\n\n| Variable | Meaning |\n|---|---|\n| `Murder` | Murder arrests per 100,000 residents |\n| `Assault` | Assault arrests per 100,000 residents |\n| `UrbanPop` | Percent of the state population living in urban areas |\n| `Rape` | Rape arrests per 100,000 residents |\n\nTwo features make it useful for teaching.\nThe row names are state names rather than a column, which is why the book indexes with `USArrests[,'Murder']` rather than by position.\nAnd the variables are rates per 100,000 rather than counts, so they are comparable across states of very different size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(USArrests)\n## [1] 50  4\nhead(USArrests, 3)\n##         Murder Assault UrbanPop Rape\n## Alabama   13.2     236       58 21.2\n## Alaska    10.0     263       48 44.5\n## Arizona    8.1     294       80 31.0\nsummary(USArrests[,'Murder'])\n##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n##   0.800   4.075   7.250   7.788  11.250  17.400\n```\n:::\n\n\nNote that these are *arrest* rates, not offense rates.\nDifferences across states reflect policing and reporting practice as well as underlying crime, which is worth remembering whenever a regression in a later chapter treats one of these variables as an outcome.\n\n#### **state.region** {-}\n\nA factor of length 50 giving the census region of each state, in the same state order as `USArrests`.\nThe four levels are Northeast, South, North Central, and West.\nThe book uses it as the example of an unordered factor and as the grouping variable for multiple-group comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(state.region)\n## state.region\n##     Northeast         South North Central          West \n##             9            16            12            13\n```\n:::\n\n\nBecause the ordering matches, you can attach it to `USArrests` directly without a merge.\n\n#### **anscombe** {-}\n\nAnscombe's quartet: four $x$ and $y$ pairs with nearly identical means, variances, correlations, and regression lines, but very different scatterplots.\nEleven rows each.\nThe book uses it to make the point that summary statistics do not determine the shape of a relationship.\n\n#### **UCBAdmissions** {-}\n\nA three-dimensional table of graduate admissions at the University of California, Berkeley, by admission outcome, gender, and department.\nThe table has two admission outcomes, two gender categories, and six departments, for $2\\times2\\times6=24$ cells.\nThe book uses it for three-way tables in Chapter 22 and for Simpson's paradox in Chapter 18.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nftable(UCBAdmissions)\n##                 Dept   A   B   C   D   E   F\n## Admit    Gender                             \n## Admitted Male        512 353 120 138  53  22\n##          Female       89  17 202 131  94  24\n## Rejected Male        313 207 205 279 138 351\n##          Female       19   8 391 244 299 317\n```\n:::\n\n\n#### **LifeCycleSavings** {-}\n\nSavings rates and demographics for fifty countries, averaged over 1960 to 1970.\n\n| Variable | Meaning |\n|---|---|\n| `sr` | Aggregate personal savings as a percent of disposable income |\n| `pop15` | Percent of the population under age 15 |\n| `pop75` | Percent of the population over age 75 |\n| `dpi` | Real per-capita disposable income, in US dollars |\n| `ddpi` | Percent growth rate of `dpi` |\n\nThe book uses it in Chapter 22 as a second dataset with several cardinal variables, since its scatterplot matrix has both tightly related pairs and a clear outlier.\n\n## Package Datasets\n\n#### **Wages1** {-}\n\nA cross-section of 3294 workers, from the `Ecdat` package.\nThis is the book's main dataset once samples need to be larger than 50.\n[Sampling & Resampling](01_05_Sampling.qmd), [Population Statistics](01_06_PopStatistics.qmd), [Confidence Intervals](01_07_Intervals.qmd), and [Hypothesis Testing](01_08_HypothesisTests.qmd) pretend its 3294 workers are the whole population, so sample statistics can be compared with a known truth.\n[Simple Regression](02_15_SimpleRegression.qmd), [Inference](02_17_Inference.qmd), [Association is not Causation](02_18_NotCausation.qmd), and [Testing Theory](02_20_StatisticalTheory.qmd) do the same with `school` and `wage`, stored in `population_xy`.\n\n| Variable | Meaning |\n|---|---|\n| `exper` | Years of work experience |\n| `sex` | `male` or `female` |\n| `school` | Years of schooling |\n| `wage` | Hourly wage |\n\nInstall the package once, then load the dataset when you need it.\n\n```r\ninstall.packages('Ecdat')   # once ever\ndata(Wages1, package='Ecdat')\n```\n\nWith $n = 3294$ the scatterplots need transparency to be readable, which is why [Figures](04_C_Figures.qmd) ties the alpha channel to sample size.\n\n## Datasets Read from the Web\n\nTwo chapters read a CSV directly from a URL rather than from a package.\nThis needs a working internet connection, and the file could change or move, which is itself a reproducibility lesson worth noticing.\n\n#### **finance-charts-apple.csv** {-}\n\nDaily Apple share prices over 506 trading days, read into an object called `stock` in Chapter 27.\nAlongside `Date` it carries `AAPL.Open`, `AAPL.High`, `AAPL.Low`, `AAPL.Close`, `AAPL.Volume`, and `AAPL.Adjusted`, plus four columns (`dn`, `mavg`, `up`, `direction`) that someone else derived from the prices before publishing the file.\nThe book uses it for time-series plots, where observations are not independent across rows.\n\n```r\nstock <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')\n```\n\n#### **tylervigen.csv** {-}\n\nA collection of unrelated time series compiled to illustrate spurious correlation, read into `vigen_csv` in Chapter 29.\nAny two of its columns will tend to correlate strongly, which is exactly the point being made.\n\n```r\nvigen_csv <- read.csv(\n    'https://raw.githubusercontent.com/the-mad-statter/whysospurious/master/data-raw/tylervigen.csv'\n)\n```\n\n## Packages\n\nR starts with a handful of packages already loaded.\nThese include `stats` for `lm()` and `loess()`, `graphics` for `plot()` and `hist()`, `grDevices` for colors such as `rgb()`, `utils` for `head()` and `read.csv()`, and `datasets` for `USArrests`.\nEvery other package must be installed once and then loaded in each session, as explained in [Data & Visualization](01_02_Data.qmd#datasets).\n[Code Conventions](04_B_CodeStyle.qmd) explains when to load a package with `library()` and when to call one function with `::`.\n\n| Package | What the book uses it for | Chapters |\n|---|---|---|\n| `Ecdat` | The `Wages1` dataset | 2, 5--8, 11--18, 20, 22, 26 |\n| `wooldridge` | The `wage1` and `countymurders` datasets | 12, 30 |\n| `mvtnorm` | Draws from a multivariate normal distribution, with `rmvnorm()` | 14, 18--19 |\n| `plotly` | Interactive figures, with `plot_ly()` | 15, 21, 23, 27 |\n| `reactable` | Interactive tables | 21 |\n| `stargazer` | Formatted regression and summary tables | 21, 28--29 |\n| `psych` | Scatterplot matrices, with `pairs.panels()` | 22 |\n| `fixest` | Fixed-effects and instrumental-variable regressions, with `feols()` | 24, 28--29 |\n| `sf` | Vector spatial data, such as county borders | 27 |\n| `terra` | Raster spatial data, such as an elevation grid | 27 |\n| `units` | Attaching units such as kilometers to distances | 27 |\n| `knitr` | Placing images and tables on the page, in code the book hides | 1, 17, 21 |\n\nYou can install all of them in one line.\n\n```r\n# Run once, in the console, not in your script\ninstall.packages(c('Ecdat', 'wooldridge', 'mvtnorm', 'plotly', 'reactable',\n    'stargazer', 'psych', 'fixest', 'sf', 'terra', 'units', 'knitr'))\n```\n\nOn Windows and macOS these install like any other package.\nOn Linux, `sf` and `terra` also need the system libraries GDAL, GEOS, and PROJ.\n\nSome chapters also name a package in a comment or in the text, as a pointer to a ready-made version of something the chapter builds by hand.\nYou do not need these to run the book's code.\n\n| Package | Named for | Chapter |\n|---|---|---|\n| `spatstat.univar` | Weighted quantiles | 3 |\n| `VGAM` | The Dagum distribution | 10 |\n| `DescTools` | Cramer's V | 14 |\n| `strucchange` | The Chow test for a structural break | 26 |\n| `segmented` | Regression with an estimated break point | 26 |\n| `ivreg` | Instrumental-variable regression | 28 |\n| `car` | Variance inflation factors, as an example of `::` | Appendix B |\n\n:::{.callout-tip icon=false collapse=\"true\" title=\"Test Yourself\"}\nChapter 22 draws a scatterplot matrix with `psych::pairs.panels()`.\nRestart R and run `pairs.panels(USArrests)` without the `psych::` prefix.\nWhat happens, and what are two ways to fix it?\n\nR reports that it cannot find the function `pairs.panels`, because `psych` is installed but not loaded.\nEither write `psych::pairs.panels(USArrests)`, or run `library(psych)` once near the top of your script.\nIf R instead says there is no package called `psych`, then it is not installed, so run `install.packages('psych')` in the console first.\n:::\n\n#### **Further Reading** {-}\n\n* <https://vincentarelbundock.github.io/Rdatasets/datasets.html> -- a searchable index of the datasets shipped with hundreds of R packages.\n* <https://pages.stern.nyu.edu/~wgreene/Text/Edition7/tablelist8new.htm> -- the data tables from Greene's *Econometric Analysis*.\n* <https://www.ssc.wisc.edu/~bhansen/econometrics/> -- Hansen's *Econometrics* datasets.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}