# Preface {#index}

This book contains the following primers that should get you going with R in econometrics research

 * *Part   I*: Introduction to R
 * *Part  II*: Introduction to Linear Regression in R
 * *Part III*: Introduction to Reproducible Research in R
 * *Part  IV*: Intermediate R

Much of the R-programming material (I, III, IV) was copied or modified from elsewhere, especially https://r4ds.had.co.nz/ and https://adv-r.hadley.nz/ but also many other sources I have found online and elsewhere over the years. I include references when I remembered to.

Much of Part II was also copied from elsewhere, namely other econometrics textbooks. In essence, I cut a lot of material pertaining to inference with linear models and essentially treat it as a technical prerequisite to nonparametric models (taking seriously Greene's "Model Building--A General to Simple Strategy" and leaving more room for economic theory in model development and interpretation). Part II has a more humble view towards what we can say with linear models and includes a novel chapter on `Data scientism' that illustrates some of the limits and ways such models mislead rather than illuminate.

I use this book for my own teaching and not all of my materials are available online yet. It is online for my students, but an interested reader may find it useful.
